<?php

namespace App\Enums\Tenant\Product\Price;

enum Currency: string
{
    case AED = 'AED'; // United Arab Emirates Dirham
    case AFN = 'AFN'; // Afghan Afghani
    case ALL = 'ALL'; // Albanian Lek
    case AMD = 'AMD'; // Armenian Dram
    case ANG = 'ANG'; // Netherlands Antillean Guilder
    case AOA = 'AOA'; // Angolan Kwanza
    case ARS = 'ARS'; // Argentine Peso
    case AUD = 'AUD'; // Australian Dollar
    case AWG = 'AWG'; // Aruban Florin
    case AZN = 'AZN'; // Azerbaijani Manat
    case BAM = 'BAM'; // Bosnia-Herzegovina Convertible Mark
    case BBD = 'BBD'; // Barbadian Dollar
    case BDT = 'BDT'; // Bangladeshi Taka
    case BGN = 'BGN'; // Bulgarian Lev
    case BHD = 'BHD'; // Bahraini Dinar
    case BIF = 'BIF'; // Burundian Franc
    case BMD = 'BMD'; // Bermudian Dollar
    case BND = 'BND'; // Brunei Dollar
    case BOB = 'BOB'; // Bolivian Boliviano
    case BRL = 'BRL'; // Brazilian Real
    case BSD = 'BSD'; // Bahamian Dollar
    case BTN = 'BTN'; // Bhutanese Ngultrum
    case BWP = 'BWP'; // Botswana Pula
    case BYN = 'BYN'; // Belarusian Ruble
    case BZD = 'BZD'; // Belize Dollar
    case CAD = 'CAD'; // Canadian Dollar
    case CDF = 'CDF'; // Congolese Franc
    case CHF = 'CHF'; // Swiss Franc
    case CLP = 'CLP'; // Chilean Peso
    case CNY = 'CNY'; // Chinese Yuan
    case COP = 'COP'; // Colombian Peso
    case CRC = 'CRC'; // Costa Rican Colón
    case CUP = 'CUP'; // Cuban Peso
    case CVE = 'CVE'; // Cape Verdean Escudo
    case CZK = 'CZK'; // Czech Koruna
    case DJF = 'DJF'; // Djiboutian Franc
    case DKK = 'DKK'; // Danish Krone
    case DOP = 'DOP'; // Dominican Peso
    case DZD = 'DZD'; // Algerian Dinar
    case EGP = 'EGP'; // Egyptian Pound
    case ERN = 'ERN'; // Eritrean Nakfa
    case ETB = 'ETB'; // Ethiopian Birr
    case EUR = 'EUR'; // Euro
    case FJD = 'FJD'; // Fijian Dollar
    case FKP = 'FKP'; // Falkland Islands Pound
    case FOK = 'FOK'; // Faroese Króna
    case GBP = 'GBP'; // British Pound
    case GEL = 'GEL'; // Georgian Lari
    case GGP = 'GGP'; // Guernsey Pound
    case GHS = 'GHS'; // Ghanaian Cedi
    case GIP = 'GIP'; // Gibraltar Pound
    case GMD = 'GMD'; // Gambian Dalasi
    case GNF = 'GNF'; // Guinean Franc
    case GTQ = 'GTQ'; // Guatemalan Quetzal
    case GYD = 'GYD'; // Guyanese Dollar
    case HKD = 'HKD'; // Hong Kong Dollar
    case HNL = 'HNL'; // Honduran Lempira
    case HRK = 'HRK'; // Croatian Kuna
    case HTG = 'HTG'; // Haitian Gourde
    case HUF = 'HUF'; // Hungarian Forint
    case IDR = 'IDR'; // Indonesian Rupiah
    case ILS = 'ILS'; // Israeli New Shekel
    case IMP = 'IMP'; // Isle of Man Pound
    case INR = 'INR'; // Indian Rupee
    case IQD = 'IQD'; // Iraqi Dinar
    case IRR = 'IRR'; // Iranian Rial
    case ISK = 'ISK'; // Icelandic Króna
    case JEP = 'JEP'; // Jersey Pound
    case JMD = 'JMD'; // Jamaican Dollar
    case JOD = 'JOD'; // Jordanian Dinar
    case JPY = 'JPY'; // Japanese Yen
    case KES = 'KES'; // Kenyan Shilling
    case KGS = 'KGS'; // Kyrgyzstani Som
    case KHR = 'KHR'; // Cambodian Riel
    case KID = 'KID'; // Kiribati Dollar
    case KMF = 'KMF'; // Comorian Franc
    case KRW = 'KRW'; // South Korean Won
    case KWD = 'KWD'; // Kuwaiti Dinar
    case KYD = 'KYD'; // Cayman Islands Dollar
    case KZT = 'KZT'; // Kazakhstani Tenge
    case LAK = 'LAK'; // Lao Kip
    case LBP = 'LBP'; // Lebanese Pound
    case LKR = 'LKR'; // Sri Lankan Rupee
    case LRD = 'LRD'; // Liberian Dollar
    case LSL = 'LSL'; // Lesotho Loti
    case LYD = 'LYD'; // Libyan Dinar
    case MAD = 'MAD'; // Moroccan Dirham
    case MDL = 'MDL'; // Moldovan Leu
    case MGA = 'MGA'; // Malagasy Ariary
    case MKD = 'MKD'; // Macedonian Denar
    case MMK = 'MMK'; // Myanmar Kyat
    case MNT = 'MNT'; // Mongolian Tögrög
    case MOP = 'MOP'; // Macanese Pataca
    case MRU = 'MRU'; // Mauritanian Ouguiya
    case MUR = 'MUR'; // Mauritian Rupee
    case MVR = 'MVR'; // Maldivian Rufiyaa
    case MWK = 'MWK'; // Malawian Kwacha
    case MXN = 'MXN'; // Mexican Peso
    case MYR = 'MYR'; // Malaysian Ringgit
    case MZN = 'MZN'; // Mozambican Metical
    case NAD = 'NAD'; // Namibian Dollar
    case NGN = 'NGN'; // Nigerian Naira
    case NIO = 'NIO'; // Nicaraguan Córdoba
    case NOK = 'NOK'; // Norwegian Krone
    case NPR = 'NPR'; // Nepalese Rupee
    case NZD = 'NZD'; // New Zealand Dollar
    case OMR = 'OMR'; // Omani Rial
    case PAB = 'PAB'; // Panamanian Balboa
    case PEN = 'PEN'; // Peruvian Sol
    case PGK = 'PGK'; // Papua New Guinean Kina
    case PHP = 'PHP'; // Philippine Peso
    case PKR = 'PKR'; // Pakistani Rupee
    case PLN = 'PLN'; // Polish Złoty
    case PYG = 'PYG'; // Paraguayan Guaraní
    case QAR = 'QAR'; // Qatari Riyal
    case RON = 'RON'; // Romanian Leu
    case RSD = 'RSD'; // Serbian Dinar
    case RUB = 'RUB'; // Russian Ruble
    case RWF = 'RWF'; // Rwandan Franc
    case SAR = 'SAR'; // Saudi Riyal
    case SBD = 'SBD'; // Solomon Islands Dollar
    case SCR = 'SCR'; // Seychellois Rupee
    case SDG = 'SDG'; // Sudanese Pound
    case SEK = 'SEK'; // Swedish Krona
    case SGD = 'SGD'; // Singapore Dollar
    case SHP = 'SHP'; // Saint Helena Pound
    case SLE = 'SLE'; // Sierra Leonean Leone
    case SLL = 'SLL'; // Old Leone
    case SOS = 'SOS'; // Somali Shilling
    case SRD = 'SRD'; // Surinamese Dollar
    case SSP = 'SSP'; // South Sudanese Pound
    case STN = 'STN'; // São Tomé and Príncipe Dobra
    case SYP = 'SYP'; // Syrian Pound
    case SZL = 'SZL'; // Eswatini Lilangeni
    case THB = 'THB'; // Thai Baht
    case TJS = 'TJS'; // Tajikistani Somoni
    case TMT = 'TMT'; // Turkmenistani Manat
    case TND = 'TND'; // Tunisian Dinar
    case TOP = 'TOP'; // Tongan Paʻanga
    case TRY = 'TRY'; // Turkish Lira
    case TTD = 'TTD'; // Trinidad and Tobago Dollar
    case TVD = 'TVD'; // Tuvaluan Dollar
    case TWD = 'TWD'; // New Taiwan Dollar
    case TZS = 'TZS'; // Tanzanian Shilling
    case UAH = 'UAH'; // Ukrainian Hryvnia
    case UGX = 'UGX'; // Ugandan Shilling
    case USD = 'USD'; // United States Dollar
    case UYU = 'UYU'; // Uruguayan Peso
    case UZS = 'UZS'; // Uzbekistani So'm
    case VES = 'VES'; // Venezuelan Bolívar Soberano
    case VND = 'VND'; // Vietnamese Đồng
    case VUV = 'VUV'; // Vanuatu Vatu
    case WST = 'WST'; // Samoan Tālā
    case XAF = 'XAF'; // Central African CFA Franc
    case XCD = 'XCD'; // East Caribbean Dollar
    case XOF = 'XOF'; // West African CFA Franc
    case XPF = 'XPF'; // CFP Franc
    case YER = 'YER'; // Yemeni Rial
    case ZAR = 'ZAR'; // South African Rand
    case ZMW = 'ZMW'; // Zambian Kwacha
    case ZWL = 'ZWL'; // Zimbabwean Dollar

    public function label(): string
    {
        return match ($this) {
            self::AED => 'United Arab Emirates Dirham (AED)',
            self::AFN => 'Afghan Afghani (AFN)',
            self::ALL => 'Albanian Lek (ALL)',
            self::AMD => 'Armenian Dram (AMD)',
            self::ANG => 'Netherlands Antillean Guilder (ANG)',
            self::AOA => 'Angolan Kwanza (AOA)',
            self::ARS => 'Argentine Peso (ARS)',
            self::AUD => 'Australian Dollar (AUD)',
            self::AWG => 'Aruban Florin (AWG)',
            self::AZN => 'Azerbaijani Manat (AZN)',
            self::BAM => 'Bosnia-Herzegovina Convertible Mark (BAM)',
            self::BBD => 'Barbadian Dollar (BBD)',
            self::BDT => 'Bangladeshi Taka (BDT)',
            self::BGN => 'Bulgarian Lev (BGN)',
            self::BHD => 'Bahraini Dinar (BHD)',
            self::BIF => 'Burundian Franc (BIF)',
            self::BMD => 'Bermudian Dollar (BMD)',
            self::BND => 'Brunei Dollar (BND)',
            self::BOB => 'Bolivian Boliviano (BOB)',
            self::BRL => 'Brazilian Real (BRL)',
            self::BSD => 'Bahamian Dollar (BSD)',
            self::BTN => 'Bhutanese Ngultrum (BTN)',
            self::BWP => 'Botswana Pula (BWP)',
            self::BYN => 'Belarusian Ruble (BYN)',
            self::BZD => 'Belize Dollar (BZD)',
            self::CAD => 'Canadian Dollar (CAD)',
            self::CDF => 'Congolese Franc (CDF)',
            self::CHF => 'Swiss Franc (CHF)',
            self::CLP => 'Chilean Peso (CLP)',
            self::CNY => 'Chinese Yuan (CNY)',
            self::COP => 'Colombian Peso (COP)',
            self::CRC => 'Costa Rican Colón (CRC)',
            self::CUP => 'Cuban Peso (CUP)',
            self::CVE => 'Cape Verdean Escudo (CVE)',
            self::CZK => 'Czech Koruna (CZK)',
            self::DJF => 'Djiboutian Franc (DJF)',
            self::DKK => 'Danish Krone (DKK)',
            self::DOP => 'Dominican Peso (DOP)',
            self::DZD => 'Algerian Dinar (DZD)',
            self::EGP => 'Egyptian Pound (EGP)',
            self::ERN => 'Eritrean Nakfa (ERN)',
            self::ETB => 'Ethiopian Birr (ETB)',
            self::EUR => 'Euro (EUR)',
            self::FJD => 'Fijian Dollar (FJD)',
            self::FKP => 'Falkland Islands Pound (FKP)',
            self::FOK => 'Faroese Króna (FOK)',
            self::GBP => 'British Pound Sterling (GBP)',
            self::GEL => 'Georgian Lari (GEL)',
            self::GGP => 'Guernsey Pound (GGP)',
            self::GHS => 'Ghanaian Cedi (GHS)',
            self::GIP => 'Gibraltar Pound (GIP)',
            self::GMD => 'Gambian Dalasi (GMD)',
            self::GNF => 'Guinean Franc (GNF)',
            self::GTQ => 'Guatemalan Quetzal (GTQ)',
            self::GYD => 'Guyanese Dollar (GYD)',
            self::HKD => 'Hong Kong Dollar (HKD)',
            self::HNL => 'Honduran Lempira (HNL)',
            self::HRK => 'Croatian Kuna (HRK)',
            self::HTG => 'Haitian Gourde (HTG)',
            self::HUF => 'Hungarian Forint (HUF)',
            self::IDR => 'Indonesian Rupiah (IDR)',
            self::ILS => 'Israeli New Shekel (ILS)',
            self::IMP => 'Isle of Man Pound (IMP)',
            self::INR => 'Indian Rupee (INR)',
            self::IQD => 'Iraqi Dinar (IQD)',
            self::IRR => 'Iranian Rial (IRR)',
            self::ISK => 'Icelandic Króna (ISK)',
            self::JEP => 'Jersey Pound (JEP)',
            self::JMD => 'Jamaican Dollar (JMD)',
            self::JOD => 'Jordanian Dinar (JOD)',
            self::JPY => 'Japanese Yen (JPY)',
            self::KES => 'Kenyan Shilling (KES)',
            self::KGS => 'Kyrgyzstani Som (KGS)',
            self::KHR => 'Cambodian Riel (KHR)',
            self::KID => 'Kiribati Dollar (KID)',
            self::KMF => 'Comorian Franc (KMF)',
            self::KRW => 'South Korean Won (KRW)',
            self::KWD => 'Kuwaiti Dinar (KWD)',
            self::KYD => 'Cayman Islands Dollar (KYD)',
            self::KZT => 'Kazakhstani Tenge (KZT)',
            self::LAK => 'Lao Kip (LAK)',
            self::LBP => 'Lebanese Pound (LBP)',
            self::LKR => 'Sri Lankan Rupee (LKR)',
            self::LRD => 'Liberian Dollar (LRD)',
            self::LSL => 'Lesotho Loti (LSL)',
            self::LYD => 'Libyan Dinar (LYD)',
            self::MAD => 'Moroccan Dirham (MAD)',
            self::MDL => 'Moldovan Leu (MDL)',
            self::MGA => 'Malagasy Ariary (MGA)',
            self::MKD => 'Macedonian Denar (MKD)',
            self::MMK => 'Myanmar Kyat (MMK)',
            self::MNT => 'Mongolian Tögrög (MNT)',
            self::MOP => 'Macanese Pataca (MOP)',
            self::MRU => 'Mauritanian Ouguiya (MRU)',
            self::MUR => 'Mauritian Rupee (MUR)',
            self::MVR => 'Maldivian Rufiyaa (MVR)',
            self::MWK => 'Malawian Kwacha (MWK)',
            self::MXN => 'Mexican Peso (MXN)',
            self::MYR => 'Malaysian Ringgit (MYR)',
            self::MZN => 'Mozambican Metical (MZN)',
            self::NAD => 'Namibian Dollar (NAD)',
            self::NGN => 'Nigerian Naira (NGN)',
            self::NIO => 'Nicaraguan Córdoba (NIO)',
            self::NOK => 'Norwegian Krone (NOK)',
            self::NPR => 'Nepalese Rupee (NPR)',
            self::NZD => 'New Zealand Dollar (NZD)',
            self::OMR => 'Omani Rial (OMR)',
            self::PAB => 'Panamanian Balboa (PAB)',
            self::PEN => 'Peruvian Sol (PEN)',
            self::PGK => 'Papua New Guinean Kina (PGK)',
            self::PHP => 'Philippine Peso (PHP)',
            self::PKR => 'Pakistani Rupee (PKR)',
            self::PLN => 'Polish Złoty (PLN)',
            self::PYG => 'Paraguayan Guaraní (PYG)',
            self::QAR => 'Qatari Riyal (QAR)',
            self::RON => 'Romanian Leu (RON)',
            self::RSD => 'Serbian Dinar (RSD)',
            self::RUB => 'Russian Ruble (RUB)',
            self::RWF => 'Rwandan Franc (RWF)',
            self::SAR => 'Saudi Riyal (SAR)',
            self::SBD => 'Solomon Islands Dollar (SBD)',
            self::SCR => 'Seychellois Rupee (SCR)',
            self::SDG => 'Sudanese Pound (SDG)',
            self::SEK => 'Swedish Krona (SEK)',
            self::SGD => 'Singapore Dollar (SGD)',
            self::SHP => 'Saint Helena Pound (SHP)',
            self::SLE => 'Sierra Leonean Leone (SLE)',
            self::SLL => 'Sierra Leonean Leone (SLL)',
            self::SOS => 'Somali Shilling (SOS)',
            self::SRD => 'Surinamese Dollar (SRD)',
            self::SSP => 'South Sudanese Pound (SSP)',
            self::STN => 'São Tomé and Príncipe Dobra (STN)',
            self::SYP => 'Syrian Pound (SYP)',
            self::SZL => 'Eswatini Lilangeni (SZL)',
            self::THB => 'Thai Baht (THB)',
            self::TJS => 'Tajikistani Somoni (TJS)',
            self::TMT => 'Turkmenistani Manat (TMT)',
            self::TND => 'Tunisian Dinar (TND)',
            self::TOP => 'Tongan Paʻanga (TOP)',
            self::TRY => 'Turkish Lira (TRY)',
            self::TTD => 'Trinidad and Tobago Dollar (TTD)',
            self::TVD => 'Tuvaluan Dollar (TVD)',
            self::TWD => 'New Taiwan Dollar (TWD)',
            self::TZS => 'Tanzanian Shilling (TZS)',
            self::UAH => 'Ukrainian Hryvnia (UAH)',
            self::UGX => 'Ugandan Shilling (UGX)',
            self::USD => 'United States Dollar (USD)',
            self::UYU => 'Uruguayan Peso (UYU)',
            self::UZS => 'Uzbekistani So\'m (UZS)',
            self::VES => 'Venezuelan Bolívar Soberano (VES)',
            self::VND => 'Vietnamese Đồng (VND)',
            self::VUV => 'Vanuatu Vatu (VUV)',
            self::WST => 'Samoan Tālā (WST)',
            self::XAF => 'Central African CFA Franc (XAF)',
            self::XCD => 'East Caribbean Dollar (XCD)',
            self::XOF => 'West African CFA Franc (XOF)',
            self::XPF => 'CFP Franc (XPF)',
            self::YER => 'Yemeni Rial (YER)',
            self::ZAR => 'South African Rand (ZAR)',
            self::ZMW => 'Zambian Kwacha (ZMW)',
            self::ZWL => 'Zimbabwean Dollar (ZWL)',
        };
    }

    public static function selectOptions(): array
    {
        return collect(Currency::cases())
            ->map(fn(Currency $currency) => [
                'name' => $currency->label(),
                'value' => $currency->value,
            ])->toArray();
    }
}
